### ISSUE TITLE
Examples: demo.opengeo.org does not send CORS headers in response

### ISSUE THREAD

**Issue by justb4** [openlayers/ol3-cesium#127]
Cesium apps obtain images via XHR. For this to work either a proxy needs to be present or the web (e.g. Apache) server needs to add "CORS Headers". OL3-Cesium examples that use demo.opengeo.org like http://openlayers.org/ol3-cesium/examples/synthvectors.html give:

*Image from origin 'http://demo.opengeo.org' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource.*

This can be resolved by e.g. Apache setting CORS headers, e.g. 

         Header set Access-Control-Allow-Origin "*"

Well you most surely know this :-) but maybe this setting disappeared with e.g. an upgrade.

Great work btw you are doing!!

**Comment by fegyi001** [comment]
Hello everyone,

I am quite new to OL3 & Cesium, but find it extremely exciting!
I have the same problem Just had, the same origin policy issue:

"Image from origin 'http://localhost:8061' has been blocked from loading by Cross-Origin Resource Sharing policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://localhost' is therefore not allowed access."

My application runs on localhost, and I have a GeoServer on localhost:8061.

I added the extra line for setting CORS headers, restarted Apache, but the error is still there.

Here is my httpd.conf. What is wrong with it?

***********************************************************************

        ServerRoot "C:/Programok/ms4w/Apache"

        Listen 80

        LoadModule actions_module modules/mod_actions.so
        LoadModule alias_module modules/mod_alias.so
        LoadModule asis_module modules/mod_asis.so
        LoadModule auth_basic_module modules/mod_auth_basic.so
        LoadModule authn_default_module modules/mod_authn_default.so
        LoadModule authn_file_module modules/mod_authn_file.so
        LoadModule authz_default_module modules/mod_authz_default.so
        LoadModule authz_groupfile_module modules/mod_authz_groupfile.so
        LoadModule authz_host_module modules/mod_authz_host.so
        LoadModule authz_user_module modules/mod_authz_user.so
        LoadModule autoindex_module modules/mod_autoindex.so
        LoadModule cgi_module modules/mod_cgi.so
        LoadModule dir_module modules/mod_dir.so
        LoadModule env_module modules/mod_env.so
        LoadModule headers_module modules/mod_headers.so
        LoadModule include_module modules/mod_include.so
        LoadModule isapi_module modules/mod_isapi.so
        LoadModule log_config_module modules/mod_log_config.so
        LoadModule mime_module modules/mod_mime.so
        LoadModule negotiation_module modules/mod_negotiation.so
        LoadModule setenvif_module modules/mod_setenvif.so

        <IfModule !mpm_netware_module>
        <IfModule !mpm_winnt_module>

        User daemon
        Group daemon

        </IfModule>
        </IfModule>

        ServerAdmin admin@example.com

        DocumentRoot "C:/Programok/ms4w/Apache/htdocs"


        Header set Access-Control-Allow-Origin "*"
        #Header set Access-Control-Allow-Headers "Origin, X-Requested-With, Content-Type, Accept"
        #Header set Access-Control-Allow-Methods "GET, PUT, POST, DELETE"

        <Directory />
            Options FollowSymLinks
            AllowOverride None
            Order deny,allow
            Deny from all
        </Directory>

        <Directory "C:/Programok/ms4w/Apache/htdocs">
            Options Indexes FollowSymLinks
            AllowOverride None
            Order allow,deny
            Allow from all
        </Directory>

        <IfModule dir_module>
            DirectoryIndex index.html index.html.var index.php index.phtml index.php3
        </IfModule>

        <FilesMatch "^\.ht">
            Order allow,deny
            Deny from all
            Satisfy All
        </FilesMatch>

        ErrorLog "logs/error.log"

        LogLevel warn

        <IfModule log_config_module>
            LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\"" combined
            LogFormat "%h %l %u %t \"%r\" %>s %b" common

            <IfModule logio_module>
              LogFormat "%h %l %u %t \"%r\" %>s %b \"%{Referer}i\" \"%{User-Agent}i\" %I %O" combinedio
            </IfModule>

            CustomLog "logs/access.log" common
        </IfModule>

        <IfModule alias_module>
            ScriptAlias /cgi-bin/ "C:/Programok/ms4w/Apache/cgi-bin/"
            ScriptAlias /fcgi-bin/ "C:/Programok/ms4w/Apache/cgi-bin/" 
            Alias /ms_tmp/ "C:/Programok/ms4w/tmp/ms_tmp/"      

        </IfModule>

        <IfModule cgid_module>
        </IfModule>

        <Location "/cgi-bin">
            AllowOverride None
            Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
            Order allow,deny
            Allow from all
        </Location>

        <Location "/fcgi-bin">
            SetHandler fcgid-script
            Options None
            Order allow,deny
            Allow from all
        </Location>

        <Directory "C:/Programok/ms4w/tmp/">
            AllowOverride None
            Options None
            Order allow,deny
            Allow from all
        </Directory>

        DefaultType text/plain

        <IfModule mime_module>
            TypesConfig conf/mime.types

            AddType application/x-compress .Z
            AddType application/x-gzip .gz .tgz

            AddType application/x-httpd-php .php5 .php4 .php3 .phtml .php
            Action  application/x-httpd-php /cgi-bin/php-cgi.exe  
            
        </IfModule>

        Include conf/extra/httpd-autoindex.conf
        <IfModule ssl_module>
        SSLRandomSeed startup builtin
        SSLRandomSeed connect builtin
        </IfModule>

        SetEnv PROJ_LIB "C:/Programok/ms4w/proj/nad/"
        SetEnv PATH "C:/Programok/ms4w/Apache/cgi-bin/" 

        include "C:/Programok/ms4w/httpd.d/httpd_*.conf"

        SetEnv GDAL_DATA "C:/Programok/ms4w/gdaldata"

        SetEnv GDAL_DRIVER_PATH "C:/Programok/ms4w/gdalplugins"

        SetEnv TMP "C:/Programok/ms4w/tmp"

        SetEnv CURL_CA_BUNDLE "C:/Programok/ms4w/Apache/conf/ca-bundle/cacert.pem"

**Comment by justb4** [comment]
@fegyi001 Looks like the error comes from GeoServer: are you sure that your requests go through Apache first via a (AJP)-Proxy and not directly to GeoServer? Otherwise, if you use Tomcat, you may enable CORS in Tomcat: http://tomcat.apache.org/tomcat-7.0-doc/config/filter.html#CORS_Filter. Not sure if you use Jetty servlet container (default GeoServer .exe I think). 

Strictly your question is not related to the original issue but alas :-).

**Comment by fredj** [comment]
CORS header from `http://demo.boundlessgeo.com/geoserver/wms` has been fixed

**Comment by fegyi001** [comment]
Thank you everyone!

2015-06-30 13:40 GMT+02:00 Frédéric Junod <notifications@github.com>:
