### ISSUE TITLE
Need clarification on dependencies (OL and Cesium)

### ISSUE THREAD

**Issue by vog** [openlayers/ol3-cesium#154]
From the documentation it is not clear in how far OL3-Cesium depends on certain OpenLayers and/or Cesium versions.

The release archive ships with certain OL and Cesium versions, but is this really how OL3-Cesium is meant to be used in larger applications? Can it be combined with other versions of OL and Cesium, or does it depend on some internal details of these specific shipped versions? Are these shipped versions original ones, or do they contain some additional patches?

It would be nice to have some documentation (e.g. NPM style `package.json`) which states exactly which versions of OL and Cesium should be used in combination with OL3-Cesium v1.0.0.

**Comment by gberaudo** [comment]
Recently, Ol3 and Cesium are both releasing a stable version every month. Ol3-Cesium is going to adopt the same release frequency and be tested using the latest stable Ol3 and Cesium versions.

I am going to release a v1.1 of ol3-cesium this week, based on the stables OL 3.1.1 and Cesium 1.5 releases and add a note on github.

Of course, other versions may work, but it is your responsibility to test. There are currently no dependencies on internal details.

Does it answer your concerns?

**Comment by vog** [comment]
Thanks for the clarification!
