### ISSUE TITLE
Questions about release 1.1

### ISSUE THREAD

**Issue by vog** [openlayers/ol3-cesium#156]
Sorry in advance if this is just me being too impatient, but I have the following questions regarding release 1.1:

https://github.com/openlayers/ol3-cesium/releases/tag/v1.1

1. There is no build (yet), just the source packages. Are these about to be provided, or have these been omitted by accident?
2. Will there be a debug build in that release? Or, are all OL3-Cesium users supposed to create their own build setup to debug issues in OL3-Cesium?
3. Shouldn't the release number be "1.1.0" and the tag be "v1.1.0" instead of "v1.1"?

**Comment by gberaudo** [comment]
Hi @vog, we are moving to a policy similar to Cesium bX:
- monthly releases;
- changes in the CHANGES.md.

Please see https://github.com/openlayers/ol3-cesium/issues/149 for details on the project discussion.
I will update the wiki shortly to summarize it and add the release zip. I will also update the examples.

Thanks for the report.
