### ISSUE TITLE
Unable to load features without geometries

### ISSUE THREAD

**Issue by vog** [openlayers/ol3-cesium#161]
While OL3 is perfectly capable of handling features which don't contain geometries, OL3-Cesium is not.

This may happen, for example, when loading GeoJSON data. Features without geometries [are perfectly valid GeoJSON](http://geojson.org/geojson-spec.html#feature-objects) data.

Consider the following valid GeoJSON structure:

<pre>
var geoJsonData = {
    "type": "FeatureCollection",
    "features": [
        {
            "type": "Feature",
            "id": "SOME_ID",
            "geometry": null,
            "properties": {
                "designator": "SOME_DESIGNATOR"
            }
        }
    ]
};
var features = new ol.format.GeoJSON().readFeatures(geoJsonData);
</pre>

When loading this into a vector source of a map with activated OL3-Cesium:

<pre>
someVectorSource.addFeatures(features);
</pre>

the following error message is thrown:

<pre>
Uncaught TypeError: Cannot read property 'getType' of null
</pre>

For reference, this is the workaround I'm currently using:

<pre>
var features = new ol.format.GeoJSON().readFeatures(geoJsonData);
features = features.filter(function(feature) {
    return feature.getGeometry() !== null;
});
someVectorSource.addFeatures(features);
</pre>

**Comment by gberaudo** [comment]
Thank you for pointing this and for the workaround.
The PR #162 will fix the issue in next release.
