### ISSUE TITLE
3d model in ol3-cesium

### ISSUE THREAD

**Issue by FizrukBet** [openlayers/ol3-cesium#163]
Can I add a 3d model(using ol3-secium), similar as here https://cesiumjs.org/2014/03/03/Cesium-3D-Models-Tutorial?

**Comment by gberaudo** [comment]
Could you detail what you expect to see in the 2D map?

**Comment by FizrukBet** [comment]
The 2D view suits me, but i have problem with 3D view http://gyazo.com/7dfd0b4ce3b17a540d489648782915d8

var ol2d = new ol.Map({
  layers: [
    new ol.layer.Tile({
      source: new ol.source.BingMaps({
      key: 'Ak-dzM4wZjSqTlzveKz5u0d4IQ4bRzVI309GxmkgSVr1ewS6iPSrOvOKhA-CJlm3',
      imagerySet: 'Aerial'
    })
    })
  ],
  controls: ol.control.defaults({
    attributionOptions: /** @type {olx.control.AttributionOptions} */ ({
      collapsible: false
    })
  }),
  target: 'map',
  view: new ol.View({
    center: ol.proj.transform([27.551624,53.891057], 'EPSG:4326', 'EPSG:3857'),
	zoom: 11
  })
});

var ol3d = new olcs.OLCesium({map: ol2d});
var scene = ol3d.getCesiumScene();

var modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(
    Cesium.Cartesian3.fromDegrees(27.550770,53.890550, 0.0));
var model = scene.primitives.add(Cesium.Model.fromGltf({
    url : '/apps/SampleData/models/voczal/models/model.gltf',
    modelMatrix : modelMatrix
}));

var terrainProvider = new Cesium.CesiumTerrainProvider({
    url : '//cesiumjs.org/stk-terrain/tilesets/world/tiles'
});
scene.terrainProvider = terrainProvider;

**Comment by gberaudo** [comment]
Your code is almost correct; you just forget the station elevation in
the model matrix, which should be around 280m in Minsk.

Additionally, you may want to set `globe.depthTestAgainstTerrain` to `true`.

**Comment by FizrukBet** [comment]
many thanks for your answer, it works!
