### ISSUE TITLE
Polygon extrusion support

### ISSUE THREAD

**Issue by FizrukBet** [openlayers/ol3-cesium#167]
can i add kml data to map with ol3-cesium similar as this http://gyazo.com/72cf07ad72afb32f722a8fb14501f8ba
?

**Comment by ahocevar** [comment]
ol3-cesium does not support extrusion like that natively. However, once your KML is loaded into ol3, you can programmatically extrude the geometries.

Having said that, native extrusion support would be a nice feature to have.

**Comment by FizrukBet** [comment]
thanks for the answer, maybe you have some information about extrude the geometries with ol3?

**Comment by gberaudo** [comment]
Hi @FizrukBet, this should be an easy contribution:
- In OL3, add parsing support for the `extrude` tag to `src/ol/format/kmlformat.js` and a new property in the `ol.geom.Polygon` geometry.
- In Ol3-cesium, enhance `olcs.core.olPolygonGeometryToCesium to read the extrusion value from the Ol3 geometry and set it in the Primitive like in Cesium Sandcastle example: https://cesiumjs.org/Cesium/Apps/Sandcastle/index.html?src=Geometry%20and%20Appearances.html&label=Showcases .

Another possibility is to use the KML branch from Cesium and bypass ol3-cesium for this layer; however you would lose automatic synchronization

**Comment by FizrukBet** [comment]
Thanks for your answer, but I can't still understand what I have to do for success.

1) Maybe you will show on an example, how I can make extrude for this source:

var source = new ol.source.GeoJSON({
    projection: 'EPSG:3857',
    url: 'data/geojson/build.geojson'
});

var vector = new ol.layer.Vector({
  source: source
});

var ol2d = new ol.Map({
  layers: [
    new ol.layer.Tile({
      source: new ol.source.OSM()
    }),
	vector
  ],
  target: 'map',
  view: new ol.View({
    center: ol.proj.transform([25, 20], 'EPSG:4326', 'EPSG:3857'),
    zoom: 3
  })
});

var ol3d = new olcs.OLCesium(ol2d);


Or
2) How i can repeat this code in ol-cesium
var viewer = new Cesium.Viewer('cesiumContainer');
    var dataSource = new Cesium.GeoJsonDataSource();
    viewer.dataSources.add(dataSource);
    dataSource.loadUrl('/apps/SampleData/build.geojson').then(function() {
        var entities = dataSource.entities.values;
        for (var i = 0; i < entities.length; i++) {
            var entity = entities[i];
            var name = entity.name;
            entity.polygon.material = new Cesium.Color(1, 1, 1, 1);
            entity.polygon.outlineColor = Cesium.Color.BLACK;
            entity.polygon.extrudedHeight = entity.properties.HEIGHT;
        }
    });

i'm sorry if my questions are stupid

**Comment by gberaudo** [comment]
We were speaking about KML; is there a concept of extruded data in geojson? Maybe in a property? What does your build.geojson contain?

Unfortunately, Cesium moved all their Sandcastle examples to higher level `entities` API. Please build and run locally the Sandcastle of Cesium version 1.5 and look at the geometry and appearance example. I updated the Sandcastle link above. You should update your code to use the low-level API.

**Comment by FizrukBet** [comment]
I think that the algorithm  for kml and geojson has to be identical. geojson is a polygonal layer with attribute of height ('HEIGHT') for each polygon. 

I think that I have to for everyone ol.feature make cesium primitive. I'm trying to use olcs.core.olPolygonGeometryToCesium, but i haven't a success

var style = new ol.style.Style({
    stroke: new ol.style.Stroke({color: 'red', width: 2})
});

var vectorSource = new ol.source.GeoJSON({
    projection: 'EPSG:3857',
    url: 'data/geojson/build.geojson'
})

var vector = new ol.layer.Vector({
    source: vectorSource,
    style: style
});

var ol2d = new ol.Map({
  layers: [
    new ol.layer.Tile({
      source: new ol.source.OSM()
    }),
    vector
  ],
  target: 'map',
  view: new ol.View({
    center: ol.proj.transform([25, 20], 'EPSG:4326', 'EPSG:3857'),
    zoom: 3
  })
});

setTimeout(function(){
    vectorSource.forEachFeature(function(feature) {

// ??????? on this line i have an error (TypeError: a.getLinearRings is not a function)
        var cesPrimitive = olcs.core.olPolygonGeometryToCesium(feature.getGeometry(), 'EPSG:4326', style);
        console.log(cesPrimitive);
    });
}, 1000);

var ol3d = new olcs.OLCesium(ol2d);

**Comment by FizrukBet** [comment]
as a result I have to receive 3D polygons in 3D view in any most suitable way

**Comment by gberaudo** [comment]
@FizrukBet, it is hard to say without being able to run the code.
See a quick hack using the selection example: https://github.com/gberaudo/ol3-cesium/tree/hack_extrusion.

**Comment by FizrukBet** [comment]
it turned out to make with my geojson, the mistake appeared on the multipolygon. Thanks for your advices.

**Comment by carlosjpr-collab** [comment]
any news for the support ? 2022
