### ISSUE TITLE
projection problem in ol3-cesium

### ISSUE THREAD

**Issue by aslam-gis** [openlayers/ol3-cesium#193]
Hi,

I am trying to plot some points in 2d as well as 3d for Delhi(India), but the points are not getting plotted on right coordinates. I tried with different projections but still having same issue.
Please find below my code below:

var point = new ol.geom.Point([obj.latitude,obj.longitude]);			  	 		   
point.transform('EPSG:4326', 'EPSG:3857');
var feature = new ol.Feature(point); 				  	 		    
feature.set('Site Name', obj.sitename);				            
vectorSource = new ol.source.Vector();
vectorSource.addFeature(feature);				            

vectorLayer = new ol.layer.Vector({
	source: vectorSource,
	style: new ol.style.Style({
		  image: new ol.style.Icon(/** @type {olx.style.IconOptions} */ ({
				anchor: [0.5, 46],
				anchorXUnits: 'fraction',
				anchorYUnits: 'pixels',
				opacity: 0.75,
				src: 'img/tower.png'
			  })),
				text: new ol.style.Text({
				  text: obj.sitename,
				  textAlign: 'center',
				  textBaseline: 'middle',
				  stroke: new ol.style.Stroke({
					color: 'magenta',
					width: 1
				  }),
				  fill: new ol.style.Fill({
					color: 'rgba(0, 0, 155, 0.3)'
				  })
				})
			})
	});

map.addLayer(vectorLayer);

**Comment by gberaudo** [comment]
Hi, the order is `lonlat` in Ol3.
See the new `ol.proj.toLonLat` and http://openlayers.org/en/v3.5.0/doc/faq.html
