### ISSUE TITLE
Maxzoom in Ol3-cesium

### ISSUE THREAD

**Issue by richa2008** [openlayers/ol3-cesium#195]
Hi,
How can we add maxzoom property in ol3-cesium.Please help.Thanks.

**Comment by gberaudo** [comment]
Hi, add it to the source tilegrid; it is plain Ol3.

**Comment by richa2008** [comment]
Hi,
I did that as : - 
view: new ol.View({
				  projection: 'EPSG:3857',
				  center : ol.proj.transform([28.6139,77.2090], 'EPSG:4326', 'EPSG:3857'),
				  zoom: 3,
                                  minZoom: 8,
                                  maxZoom : 12
			  })

But this is working only for 2D map it is not working in 3D view.

**Comment by gberaudo** [comment]
Hi @richa2008, your issue is clearer now.
Have you tried defining these zoom constraints on the sources?

Note that Cesium does not support minimum zoom level but a workaround
may be tried in Ol3-Cesium. You should have a look to
`src/core/olimageryprovider.js`.
