### ISSUE TITLE
3D map is not loading

### ISSUE THREAD

**Issue by aslam-gis** [openlayers/ol3-cesium#197]
Hi,

I am getting some errors for the past two days and my 3D map is not coming up.
Earlier it was not having any issues. These are the errors:

http://cesiumjs.org/stk-terrain/tilessets/world/tiles/layer.json Failed to load resource: the server responded with a status of 404 (Not Found)
http://cesiumjs.org/stk-terrain/tilessets/world/tiles/0/1/0.terrain?v=1.0.0 Failed to load resource: the server responded with a status of 404 (Not Found)

Please help me out as I am unable to get to any conclusion.
Is it at the API end or from my side am I making some mistakes.

Thanks,
Md. Aslam Khan

**Comment by gberaudo** [comment]
Hi, see the url at http://cesiumjs.org/Cesium/Build/Documentation/CesiumTerrainProvider.html
