### ISSUE TITLE
scene3DOnly as Option

### ISSUE THREAD

**Issue by mj6robinson** [openlayers/ol3-cesium#206]
Would be useful to set the scene3DOnly as an option rather then being hard coded to true as it currently is. 
This would enable the ability to utilise the dynamic scene switching in Cesium and use the Columbus view.

**Comment by gberaudo** [comment]
Have you tried setting it afterwards with `scene.frameState.scene3DOnly = false`?

**Comment by mj6robinson** [comment]
I do have the app working, I just thought it would make things nicer if it could be passed through as a configuration variable, something like

```javascript 
new olcs.OLCesium({ map: map, scene3DOnly: false }); 
```

Rather then having to set it after the fact.
