### ISSUE TITLE
olcs.Camera readFromView() as public API

### ISSUE THREAD

**Issue by gejgalis** [openlayers/ol3-cesium#212]
Please mark this method to be available in public API

**Comment by gberaudo** [comment]
It is conceivable to mark the method API but what is your use case?

**Comment by gejgalis** [comment]
I'm using  standalone `var camera = new olcs.Camera(scene, map)` and I'm synchronizing manually both views.

**Comment by gberaudo** [comment]
I understand, could you please create a pull request adding the `@api` annotation?

**Comment by gberaudo** [comment]
Implemented in #216.
