### ISSUE TITLE
Missing ol.tilegrid.XYZ in OpenLayers 3.7

### ISSUE THREAD

**Issue by gejgalis** [openlayers/ol3-cesium#214]
OpenLayers: `3.7`
ol3-cesium: `1.6`
Cesium: `1.11`

`ol.tilegrid.XYZ` has been changed to `ol.tilegrid.createXYZ()` in OpenLayers 3.6

**Comment by gberaudo** [comment]
Duplicate of https://github.com/openlayers/ol3-cesium/pull/201 which is underwork.
