### ISSUE TITLE
Layers always synchronized twice 

### ISSUE THREAD

**Issue by fredj** [openlayers/ol3-cesium#237]
`olcs.AbstractSynchronizer#synchronize` is always called twice when a layer is added or removed: once by `olcs.RasterSynchronizer` and once by `olcs.VectorSynchronizer`

**Comment by gberaudo** [comment]
This is expected and necessary to allow creating a vector counterpart of a
raster layer:
all the synchronizers are called and they return non-null result when they
handled the conversion.


Note that at most one synchronizer will return a non-null result with the
default synchronizers but
it is not necessary.
