### ISSUE TITLE
olPointGeometryToCesium doesn't handle case where getImage returns null

### ISSUE THREAD

**Issue by bartvde** [openlayers/ol3-cesium#245]
See: https://github.com/openlayers/ol3-cesium/blob/7fa3360e7b063b8f04dd0f057506e7c01aa6e353/src/featureconverter.js#L429:L435

```
Uncaught TypeError: Cannot read property 'getImage' of null
```

**Comment by gberaudo** [comment]
Hi Bart, what do you have in your style?

**Comment by bartvde** [comment]
This is what the style object looks like before it goes into the ol3-cesium function:

![screen shot 2015-09-24 at 19 32 26](https://cloud.githubusercontent.com/assets/319678/10080966/0ac06c90-62f3-11e5-8ee2-5e563ef6f8ef.png)
