### ISSUE TITLE
map.forEachFeatureAtPixel in 3d View

### ISSUE THREAD

**Issue by Revo86** [openlayers/ol3-cesium#296]
Hello,

first of all: cesium is awesome! I'm struggling to find a function like map.forEachFeatureAtPixel, which will work in the 3d view. I'd like to select multiple features, which overlay each other in the same location. Any help would be much appreciated!

**Comment by gberaudo** [comment]
It is not the appropriate place for Cesium API questions.
You can certainly find answers in the Cesium API reference doc or using the Cesium mailinglist
https://groups.google.com/forum/#!forum/cesium-dev.

**Comment by jmgomezpoveda** [comment]
Relevant discussion: https://github.com/openlayers/ol3-cesium/issues/344#issuecomment-214098148
