### ISSUE TITLE
Tilestream bug @ ol3d

### ISSUE THREAD

**Issue by Revo86** [openlayers/ol3-cesium#298]
The wrong extend for loading current zoom tiles seems to be calculated in 3d view. To reproduce, please go to official example : http://openlayers.org/ol3-cesium/examples/kml.html , activate 3d view and zoom in 6 times with mousewheel (standart speed). You will see a noticable border between correctly loaded tiles and interpolated tiles from earlier zoom levels. The smaller the current zoom level, the more north this border is. A version upgrade to latest version didnt fix the problem.

For a screenshot, take a look here: http://imgur.com/TpMydjq

**Comment by gberaudo** [comment]
@Revo86, where do you see a border?

**Comment by Revo86** [comment]
@gberaudo not literally a border, rather an area with sharp tiles and an area with blurred tiles. on my screenshot you can see that right south of dresden (look at osm streets style). It seems like only a few latitudes are rendered correctly.

http://jsfiddle.net/hp7z2pun/

**Comment by gberaudo** [comment]
Cesium may load different zoom levels for rendering a scene:
![zooms](https://cloud.githubusercontent.com/assets/7294662/11781687/c0c935dc-a26b-11e5-9f6c-5ed44c74e58e.png)
However I agree the OSM example looks very blurry.

**Comment by Revo86** [comment]
@gberaudo Okay I see. Is there any option to force cesium to only load tiles from the current zoom level? In my project Geoserver layers get loaded from different zoom levels and especially lines look awkward as i cant request a single tile request.

**Comment by gberaudo** [comment]
Cesium does not have a `current` zoom level. Each tile level is chosen depending on an estimation of the error on the screen. The error is computed per tile.

**Comment by Revo86** [comment]
@gberaudo okay, so how can I handle this problem?

http://i.imgur.com/1N20zVZ.jpg

**Comment by gberaudo** [comment]
@Revo86, I think there is no way to avoid the problem with raster tiles.
A solution would be to use vector data but you will certainly have challenges to implement the same styling as in 2D and I fear there is no out-of-the-box support for drawing arcs in Cesium.

**Comment by Revo86** [comment]
@gberaudo okay thank you! ill try vectors instead then
