### ISSUE TITLE
Polygon stroke not drawn when "clampToGround" active.

### ISSUE THREAD

**Issue by jacmendt** [openlayers/ol3-cesium#326]
When i use the `clampToGround` mode the polygon stroke isn't drawn anymore. I reproduced this behavior in chrome and firefox. This behavior is also visible when using the `clampToGround` mode on the [vectors example](http://openlayers.org/ol3-cesium/examples/vectors.html) and viewing the polygons on the globe.

**Comment by gberaudo** [comment]
This is expected since Cesium does not support lines on the ground yet.
Geometry outlines are not rendered.

Details in https://github.com/AnalyticalGraphicsInc/cesium/issues/2172.

**Comment by andrevall** [comment]
Is there any plan to support polygon outlines on terrain and 3dtiles?

**Comment by gberaudo** [comment]
@andrevall, no plan but pull requests are welcomed for polygon on the ground. We have also workaround code for lines which could be cleanup.

Regarding 3dtiles, what do you expect of ol-cesium?
