### ISSUE TITLE
Error when calling Cesium Scene.pick

### ISSUE THREAD

**Issue by glompos21** [openlayers/ol3-cesium#327]
I want to be able to click on a 3D object with openLayers background and display information inside a iframe. 
On my way to finish it i have encounter the following error when i have activated the 3D map and left click anywhere in the screen.

> Uncaught DeveloperError: windowPosition is undefined.
> Error
>     at new t (http://localhost/xri/ol3cesium/Cesium/Cesium.js:417:6526)
>     at ae.pick (http://localhost/xri/ol3cesium/Cesium/Cesium.js:465:3817)
>     at http://localhost/xri/ol3cesium/ol3dBox/main.js:36:27
>     at g (http://localhost/xri/ol3cesium/Cesium/Cesium.js:431:5898)
>     at HTMLDocument.n (http://localhost/xri/ol3cesium/Cesium/Cesium.js:431:4434)
>     ae.pick	@	Cesium.js:465
>     (anonymous function)	@	main.js:36
>     g	@	Cesium.js:431
>     n	@	Cesium.js:431

I have added the following code to the main.js example

```
var modelMatrix = Cesium.Transforms.eastNorthUpToFixedFrame(
Cesium.Cartesian3.fromDegrees(24,35, 0.0));
var model = scene.primitives.add(Cesium.Model.fromGltf({
id : 'testB',
url : 'testB.glb',
modelMatrix : modelMatrix
}));


// Mouse over the globe to see the cartographic position
handler = new Cesium.ScreenSpaceEventHandler(scene.canvas);
handler.setInputAction(function(movement) {
  console.log(movement);
  var pickedObject = scene.pick(movement.endPosition); // line 36
  console.log(pickedObject);
}, Cesium.ScreenSpaceEventType.LEFT_CLICK);
```

**Comment by gberaudo** [comment]
Hi, your question is unrelated to OL3-Cesium. You would probably have more answers on the Cesium mailinglist.

That beeing said, maybe your endPosition is undefined. In the Apps/Sandcastle/gallery/Picking.html
example, they are listening on mouse move and not on click event.
