### ISSUE TITLE
ol.proj.getTransform sourceprojection = null issue

### ISSUE THREAD

**Issue by pksorensen** [openlayers/ol3-cesium#338]
![image](https://cloud.githubusercontent.com/assets/2718591/14302520/2bad3e68-fba2-11e5-8c0b-1f7c6db20d55.png)

I am figthing a null error and using the -debug build I could inspect the issue in dev tools, but I got abit confused.  Is ol3cesium independent of ol3? Should we not include both ol3 and ol3 and ol3cesium files ? (could this be my issue that the view is constructed from ol.js and then ol.proj.transform do not work because of this?

**Comment by gberaudo** [comment]
OL3-Cesium used to be compiled separately from OL3.
Nowadays the result of the compilation of OL3-Cesium contains the code of OL3.
@pksorensen, are you including OL3 twice?

**Comment by pksorensen** [comment]
I was. But a few hours last night I came to the same conclussion as you just mentioned and after figuring out how to change all module loading my problems vent away. 


Can you share what stategy for keeping it updated with ol3 you are using?  is it always a month behind, by using the latest release from ol3 or is it a commit from master in between released depending on when its done?

I ask because I am almost sure that I am using a feature from ol3 that was added later than 3.14, which could be explained by the later example.

For others, my setup  in requirejs looks like this:

```
define("openLayers", ["olbundle", "css!libs/ol3/v3.15.0/ol3/ol.css"], function (bundle) { console.log(arguments); return bundle.ol });
define("ol3cesium", ["cesiumjs", "olbundle"], function (cesium, bundle) { console.log(arguments); return bundle.olcs });
   

 shim: {
        "olbundle": {
                    deps:["proj4"],
                    init: function () {
                        console.log(arguments);
                        return { olcs, ol };
                    }
         }
}    


```

which means I can lazy require cesium later, but it means that I am dependent on the ol3-cesium library. 

Is it requied toinclude ol3 source code or would it work with ol3 sideloaded if we created a separate build/distribution file.

**Comment by gberaudo** [comment]
The principle is to compile against the latest stable releases of OL3 and Cesium at the time of the OL3-Cesium release. However, it may not always be possible (unfixed regression, no release...).

Last month there was no OL3 release, so OL3-Cesium March release is compiled against an OL3 version from February.

Separate build had a lot of issues, see https://github.com/openlayers/ol3-cesium/pull/289 and is no more supported. A cool alternative would be to compile OL3 and OL3-Cesium as closure compiler modules, see [--module](https://github.com/openlayers/closure-util/blob/master/compiler-options.txt). The compiler would create several compiled files (ol3.js and ol3cesium.js) and you would be able to load ol3cesium.js later in your application.

**Comment by pksorensen** [comment]
Thanks for the update. For now I will stick with the resolution i found with loading ol3-cesium instead of ol.js and using the dummy require define calls
