### ISSUE TITLE
Error in attibutions containing arrays

### ISSUE THREAD

**Issue by jmgomezpoveda** [openlayers/ol3-cesium#341]
When attributions contain arrays, the following error is produced in olcs.core.OLImageryProvider.createCreditForSource:

> TypeError: el.getHTML(...).replace is not a function

This can happen if the ol map is created with an array, such as in:

> attributions: [new ol.Attribution({ html: ['&copy;&nbsp;xxx'] })]

**Comment by jmgomezpoveda** [comment]
I have created a pull request of the fix I have implemented in my local copy of the library. Feel free to merge it as is, or to implement any better solution.

**Comment by gberaudo** [comment]
When is this case possible?

**Comment by jmgomezpoveda** [comment]
In the description I have listed a couple of cases when the attributions end up creating an array, which is later returned by getHTML().

**Comment by jmgomezpoveda** [comment]
As discussed at https://github.com/openlayers/ol3-cesium/pull/342, this can be solved on the app side by changing the app code to:
> attributions: [new ol.Attribution({ html: '&copy;&nbsp;xxx' })]

Pending to decide if any actions are recommended in ol3 or ol3-cesium, as discussed in https://github.com/openlayers/ol3-cesium/pull/342
