### ISSUE TITLE
performance issue on adding large vector data

### ISSUE THREAD

**Issue by shreya2410** [openlayers/ol3-cesium#347]
On adding large vector data, Cesium's Globe has a huge performance issue, zoomIn and zoomOut are not at all smooth and after some time it crashes.

**Comment by gberaudo** [comment]
Do you have figures? What type of geometries is it? Is it a single layer?

**Comment by shreya2410** [comment]
Added a shape file for roads in India .. The size of file is 9.9 MB.
Loading of file is taking time and after loading zooming and moving the globe is not smooth..

**Comment by gberaudo** [comment]
Is it smooth with just OL3 (no OL3-Cesium nor Cesium)?

**Comment by shreya2410** [comment]
yes.. it is running smooth with just OL3.. Even with ol3-cesium .. 2D map is also running smooth...

**Comment by gberaudo** [comment]
Is the performance the same when you are closed to the ground and far away?

**Comment by shreya2410** [comment]
in 2D map is running smooth after loading the data whether close or far from ground..

**Comment by gberaudo** [comment]
Sure, I was referring to 3D.

**Comment by shreya2410** [comment]
loading is taking time. performance issues are there irrespective of the distance from the ground

**Comment by gberaudo** [comment]
There is an ongoing work in Cesium to implement 3D tiles. It allows to split the dataset in tiles
of different details and extents and will probably fix your performance issues.

**Comment by shreya2410** [comment]
loaded data using only cesium.It was working fine.
So, the performance issue is because of ol3-cesum or ther might be something else?

**Comment by gberaudo** [comment]
Hard to say without a running example.
How did you loaded the data in Cesium? And in OL3?

**Comment by shreya2410** [comment]
Added data through wfs request... 
But when tried through wms request .. then its working fine.
