### ISSUE TITLE
Gone is the sun in the examples

### ISSUE THREAD

**Issue by slavas62** [openlayers/ol3-cesium#352]
The new version does not show the sun

**Comment by jmgomezpoveda** [comment]
This is due to a bug in Cesium 1.19 and 1.20: https://github.com/AnalyticalGraphicsInc/cesium/issues/3800

The fix will be available in Cesium 1.21. Or you can try getting the latest version of Cesium from Git.

**Comment by jmgomezpoveda** [comment]
I just tested ol3-cesium with Cesium 1.21 and the Sun is rendered correctly.

**Comment by slavas62** [comment]
Thanks for the info. When the planned release ol3-cesium with Cesium 1.21?

**Comment by gberaudo** [comment]
There is a high chance Cesium 1.21 works out of the box with the latest release of OL3-Cesium.

**Comment by jmgomezpoveda** [comment]
@gberaudo indeed, I am using it with no issues for my use cases.
