### ISSUE TITLE
Area of polygons is different in 2D and 3D

### ISSUE THREAD

**Issue by jmgomezpoveda** [openlayers/ol3-cesium#355]
When creating a polygon in 2D, its edges follow the latitude and longitude.

However, in 3D, given the different projection, the area covered by the polygons is not the same as in 2D. Polygons are drawn in 3D following the shortest paths in that projection, not the original paths they had in 2D mode. More info: http://gis.stackexchange.com/questions/191984/openlayers-3-cesium-polygon-projection-issue

Discussing this in the Cesium-dev list (https://groups.google.com/forum/#!topic/cesium-dev/BT5z9ztSnvk) they have advised to use the "rectangle" primitive instead of the "polygon". This is working great using Cesium. However, there doesn't seem to be anything equivalent in OpenLayers and therefore ol3-cesium.

```
// Wrong rendering
viewer.entities.add({
    polygon : {
        hierarchy : Cesium.Cartesian3.fromDegreesArray([-30, 70,  0, 70,  0, 69, -30, 69, -30, 70]),
        material : Cesium.Color.RED
    }
});

// Correct rendering
viewer.entities.add({
    rectangle : {
        coordinates : Cesium.Rectangle.fromDegrees(-30, 69,  0, 70),
        material : Cesium.Color.RED
    }
});
```

It would be great if there were a way to define a Cesium "rectangle" using ol3-cesium, maybe via some new primitive, or some property that defines how edges will be drawn, and depending on which ol3-cesium translates the OpenLayers polygon into a Cesium "polygon" or a "rectangle".

**Comment by gberaudo** [comment]
Conversion of the OL3 polygon to Cesium is handled in https://github.com/openlayers/ol3-cesium/blob/6ed7dc0bfb5f0798bd68e1f2624950954eefe91e/src/featureconverter.js#L394.

The application could set a property (eg `geom.set('olcs.polygon_kind', 'rectangle)'` on the polygon geometry. Then the conversion code could detect this and use the `Cesium.RectangleGeometry` / `Cesium.RectangleOutlineGeometry`.

**Comment by jmgomezpoveda** [comment]
Yeah, that is a fine idea. How would we solve the differences between how coordinates are expressed in Cesium polygons and Cesium rectangles? Cesium rectangles have to have their coordinates expressed in just two vertices: NW, SE (in that order), whereas polygons are expressed with their 4 vertices, which can appear in any order.

If the northern vertex is not the first one, Cesium raises an exception. On the other hand, if East and West are swapped, Cesium will render the polygon around the world.

Maybe we could assume for this case that vertices are in one specific order? This is getting a bit obscure, I don't see how we could express it better other than indicating it in the documentation.

**Comment by gberaudo** [comment]
Couldn't you create an extent with `ol.extent.boundingExtent(coordinates)` and read the NW and SE values?

**Comment by jmgomezpoveda** [comment]
Thanks for the hint. I have tried adding in olPolygonGeometryToCesium the following:

```
olcs.FeatureConverter.prototype.olPolygonGeometryToCesium =
    function(layer, feature, olGeometry, projection, olStyle) {

  olGeometry = olcs.core.olGeometryCloneTo4326(olGeometry, projection);
  goog.asserts.assert(olGeometry.getType() == 'Polygon');

  var fillGeometry, outlineGeometry;
  if (true || (olGeometry.get('olcs.polygon_kind') === 'rectangle')) {
    // Extract the NW, SW vertices
    var extent = ol.extent.boundingExtent(olGeometry.getCoordinates()[0]);

    // Render the cartographic rectangle
    fillGeometry = new Cesium.RectangleGeometry({
      ellipsoid: Cesium.Ellipsoid.WGS84,
      rectangle: Cesium.Rectangle.fromDegrees(extent[0], extent[3], extent[2], extent[1])
    });

    outlineGeometry = new Cesium.RectangleOutlineGeometry({
      ellipsoid: Cesium.Ellipsoid.WGS84,
      rectangle: Cesium.Rectangle.fromDegrees(extent[0], extent[3], extent[2], extent[1])
    });
  } else {
    var rings = olGeometry.getLinearRings();
    // always update Cesium externs before adding a property
    var hierarchy = {};
    var polygonHierarchy = hierarchy;
    goog.asserts.assert(rings.length > 0);

    for (var i = 0; i < rings.length; ++i) {
      var olPos = rings[i].getCoordinates();
      var positions = olcs.core.ol4326CoordinateArrayToCsCartesians(olPos);
      goog.asserts.assert(positions && positions.length > 0);
      if (i == 0) {
        hierarchy.positions = positions;
      } else {
        hierarchy.holes = {
          // always update Cesium externs before adding a property
          positions: positions
        };
        hierarchy = hierarchy.holes;
      }
    }

    fillGeometry = new Cesium.PolygonGeometry({
      // always update Cesium externs before adding a property
      polygonHierarchy: polygonHierarchy,
      perPositionHeight: true
    });

    outlineGeometry = new Cesium.PolygonOutlineGeometry({
      // always update Cesium externs before adding a property
      polygonHierarchy: hierarchy,
      perPositionHeight: true
    });
  }

  var primitives = this.wrapFillAndOutlineGeometries(
      layer, feature, olGeometry, fillGeometry, outlineGeometry, olStyle);

  return this.addTextStyle(layer, feature, olGeometry, olStyle, primitives);
};
```

Even though coordinates look good (similar to the ones I tested in the Cesium sandcastle), nothing is rendered for some reason. Maybe I am not setting the material or something?

Also, how can I check the "olcs.polygon_kind" property? olGeometry.get('olcs.polygon_kind') always returns undefined (hence the true I have added temporarily in the check).

**Comment by jmgomezpoveda** [comment]
I just fixed the property check as "if (feature.getGeometry().get('olcs.polygon_kind') === 'rectangle')". Nothing is still rendered, though.

**Comment by gberaudo** [comment]
Strange, this should work.
I will try to find some time to look at this but probably not this week as I will be attending a conference.

**Comment by jmgomezpoveda** [comment]
It is actually working beautifully now. I had the North and South coordinates of the polygon reversed.

**Comment by jmgomezpoveda** [comment]
I have created a PR including the code for generating Cesium rectangles.
