### ISSUE TITLE
Do not support ol source has different projection with the view projection?

### ISSUE THREAD

**Issue by topwood** [openlayers/ol3-cesium#362]
I see in 'core.js':
`if (source instanceof ol.source.TileImage) {
    var projection = source.getProjection();

    if (goog.isNull(projection)) {
      // if not explicit, assume the same projection as view
      projection = viewProj;
    } else if (projection !== viewProj) {
      return null; // do not sync layers with projections different than view
    }

    var is3857 = projection === ol.proj.get('EPSG:3857');
    var is4326 = projection === ol.proj.get('EPSG:4326');`

why not sync layers with projections different than view ? As i know, Cesium support EPSG:4326 and EPSG:3857.

if i init the ol map with projection EPSG:4326, and i want to add layer with EPSG:3857, it has no problem with ol itself, but when i change the view to cesium, it does not show the EPSG:3857 layer.

how to sync it?

**Comment by gberaudo** [comment]
Have you tried removing the check? What does happen?

**Comment by topwood** [comment]
Thank you, it seem no problem when i remove the check, solved!
