### ISSUE TITLE
RenderBuffer of vector layer 

### ISSUE THREAD

**Issue by slavas62** [openlayers/ol3-cesium#388]
In release OL3-Cesium v1.20 the renderBuffer of vector layer does not display label and point symbol properly.
![image](https://cloud.githubusercontent.com/assets/9322032/18208145/e7d53ee2-7136-11e6-8cf4-2db053611533.png)

**Comment by gberaudo** [comment]
Do you mean in the OL3 map?

**Comment by gberaudo** [comment]
Have you checked the OL3 changelog? There are some lines about the renderbuffer.

**Comment by slavas62** [comment]
Yes. I use ol3-cesium for vector layer view in 2D and 3D Mode. The latest version  ol3-cesium 1.20 incorrectly displays the vector layer point objects.They are cut off by the extents of the layer -- С уважением,Вячеслав Серебряков   02.09.2016, 19:35, "gberaudo" <notifications@github.com>:Do you mean in the OL3 map?—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread. OL3-Cesium v1.20
