### ISSUE TITLE
Code running in 3.4 cannot run in 3.18

### ISSUE THREAD

**Issue by Almodovar** [openlayers/ol3-cesium#389]
I use jsonp to load layer from geoserver. The below code works under ol version 3.4 but does not work in version 3.18. 

    var subbasinJsonp = new ol.source.ServerVector({
        format: new ol.format.GeoJSON(),
        loader: function(extent, resolution, projection) {
            var url = 'http://localhost:8080/geoserver/gullycreek/ows?' +
                'service=WFS&request=GetFeature&' +
                'version=1.1.0&typename=gullycreek:subbasin&' +
                'outputFormat=text/javascript&' +
                'format_options=callback:loadFeatures&' +
                'srsname=EPSG:3857&' +
                'bbox=' + extent.join(',');

            $.ajax({
                url: url,
                dataType: 'jsonp'
            });
        },
        strategy: ol.loadingstrategy.createTile(new ol.tilegrid.XYZ({
            maxZoom: 19
        })),
        projection: 'EPSG:3857'
    });

    loadFeatures = function(response) {
        subbasinJsonp.addFeatures(subbasinJsonp.readFeatures(response));
    };

    var subbasinLayer = new ol.layer.Vector({
        source: subbasinJsonp,
        style: new ol.style.Style({
            stroke: new ol.style.Stroke({
                color: 'green',
                width: 2
            })
        })
    });

**Comment by gberaudo** [comment]
Please check https://github.com/openlayers/ol3/blob/master/changelog/upgrade-notes.md on how to upgrade to newer OL3 version.
