### ISSUE TITLE
Do thus liberary supports 3d tiles?

### ISSUE THREAD

**Issue by am2222** [openlayers/ol3-cesium#392]
Do this liberary supports 3d tiles which is deffined here?
http://cesiumjs.org/2015/08/10/Introducing-3D-Tiles/

**Comment by gberaudo** [comment]
You can use the Cesium 3d-tiles branch with OL3-Cesium.

**Comment by am2222** [comment]
It is very good,Thanks very much

**Comment by JJch331** [comment]
How cloud call the function in Ol-Cesium as in Cesium 3-Tiles as following code ?
`var tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({ url :  }));`

(the code is from : https://cesiumjs.org/Cesium/Build/Apps/Sandcastle/index.html?src=3D%20Tiles%20Photogrammetry.html&label=3D%20Tiles )

**Comment by gberaudo** [comment]
@JJch331, see the documentation or examples for how to retrieve the scene from the OLCesium object.

**Comment by JJch331** [comment]
OK, I will try to do. Thank you!!

**Comment by JJch331** [comment]
In this  OLCesium function, it seems to need two input files, one is .json another is .b3dm. 
If I have .dae file, do you  know how to converter it to b3dm ? 
I am used two tools, COLLADA2GLTF and 3d-tiles-tools, to converter it, but I can't got jason file.
Thank you.
