### ISSUE TITLE
Need Some examples to draw a 3d walls

### ISSUE THREAD

**Issue by am2222** [openlayers/ol3-cesium#393]
Hi,
I have a jeojson file which is a list of polylines with a tag of hight(here is named as gid and is only for test),
I have no Idea how to make it to draw as 3d walls using ol3-cesium, Can some one gives me some help about it?Is it even possible?
thanks 

here is my jeojson file

`

> {"type":"FeatureCollection","features":[{"type":"Feature","geometry":{"type":"MultiLineString","coordinates":[[[51.3591819401274,32.6179897622543],[51.359181564534,32.6179878762856],[51.3591776496947,32.6179889956993],[51.3591880218519,32.6181130193479],[51.3592721547809,32.6181028959682],[51.3592453431881,32.617968177036],[51.3592394492604,32.6179699291621],[51.3592401426636,32.617972460011]]]},"properties":{"gid":1}},{"type":"Feature","geometry":{"type":"MultiLineString","coordinates":[[[51.3591912577337,32.6179879371233],[51.3591903331961,32.6179844328717],[51.359218878297,32.6179768403261],[51.3592196872674,32.6179795658553]]]},"properties":{"gid":2}},{"type":"Feature","geometry":{"type":"MultiLineString","coordinates":[[[51.3592259278968,32.6181081523386],[51.3592180693265,32.6180522790521],[51.3592060503367,32.6180536418156]]]},"properties":{"gid":3}},{"type":"Feature","geometry":{"type":"MultiLineString","coordinates":[[[51.3592638339418,32.6180686322127],[51.3592333241983,32.6180727205024]]]},"properties":{"gid":4}},{"type":"Feature","geometry":{"type":"MultiLineString","coordinates":[[[51.3592319373917,32.6180653226447],[51.3592268524345,32.6180322269582],[51.3592571310436,32.6180271652639]]]},"properties":{"gid":5}},{"type":"Feature","geometry":{"type":"MultiLineString","coordinates":[[[51.3592381780211,32.6180509162886],[51.3592608291943,32.6180468279979]]]},"properties":{"gid":6}},{"type":"Feature","geometry":{"type":"MultiLineString","coordinates":[[[51.3592256967624,32.6180197674025],[51.3592215363428,32.6179956270083],[51.3591787764751,32.6180020514687]]]},"properties":{"gid":7}},{"type":"Feature","geometry":{"type":"MultiLineString","coordinates":[[[51.3591799321472,32.6180230769721],[51.3592125221004,32.6180197674025]]]},"properties":{"gid":8}}]}

`

I can Add json layer into openlayer using this code

```
`var view = new ol.View({
  center: ol.proj.transform([7.455, 46.93], 'EPSG:4326', 'EPSG:3857'),
  zoom: 13
});

var buildings = new ol.layer.Vector({
  source: new ol.source.Vector({
    url: 'data/geojson/buildings.geojson',
    attributions: [new ol.Attribution({
      html: '<a href="http://www.swisstopo.admin.ch/internet/swisstopo/en/home/products/landscape/swissBUILDINGS3D/swissBUILDINGS3D.html">Swiss Federal Office of Topography</a>'
    })],
    format: new ol.format.GeoJSON()
  }),
  style: [ new ol.style.Style({
    stroke: new ol.style.Stroke({
      color: 'grey',
      width: 2
    }),
    fill: new ol.style.Fill({
      color: 'rgba(0, 0, 255, 0.1)'
    })
  }) ]
});

var layer = new ol.layer.Tile({
  source: new ol.source.OSM()
});

var ol2d = new ol.Map({
  layers: [layer, buildings],
  target: 'map2d',
  view: view
});


var ol3d = new olcs.OLCesium({map: ol2d});
var scene = ol3d.getCesiumScene();

var terrainProvider = new Cesium.CesiumTerrainProvider({
    url : 'https://assets.agi.com/stk-terrain/world'
});
scene.terrainProvider = terrainProvider;
scene.globe.depthTestAgainstTerrain = true;
`
```

It shows my layer on 2d view but when I switch on 3d my layer disappear, I have no idea how to add hight property into cesium to show it as a 3d object or entity

**Comment by gberaudo** [comment]
Lines on terrain are not supported by Cesium at the moment.
To use walls, you can extend the OL3Cesium Feature converter.

See `olcs.FeatureConverter#convert` at https://github.com/openlayers/ol3-cesium/blob/master/src/featureconverter.js#L1010.

**Comment by am2222** [comment]
Thanks very much, You mean I have to loop all features and convert them into cesium entity? Can you please give me an example how I do it?thanks

**Comment by gberaudo** [comment]
If you follow the convert method, it calls `olFeatureToCesium`. There the kind of feature is tested; you can look how the polylines are handled.
Then you will need to create a Wall geometry like here https://cesiumjs.org/Cesium/Build/Documentation/WallGeometry.html and finally return it.
