### ISSUE TITLE
Auto render loop references old Cesium private variables

### ISSUE THREAD

**Issue by schmidtk** [openlayers/ol3-cesium#432]
If the auto render loop is enabled, it will constantly throw errors due to referencing `surface._tileLoadQueue`, which no longer exists in Cesium.

To reproduce, load the [ol3cesium example](http://openlayers.org/ol3-cesium/examples/main.html), then start the render loop:

`ol3d.enableAutoRenderLoop()`

Break on caught exceptions and you'll see the problem. It looks like there is now a `_tileLoadQueue[High|Medium|Low]`, so it will hopefully be as simple as checking all three.

**Comment by gberaudo** [comment]
Thanks for the report. Are you willing to create a PR with the fix?

**Comment by schmidtk** [comment]
I probably won't get to it until next week given my current work load, but I could submit a PR for it then.

**Comment by schmidtk** [comment]
@gberaudo Sorry for the delay - had some app release work to finish first. PR is ready when you have a moment to review.
