### ISSUE TITLE
Set clock time

### ISSUE THREAD

**Issue by christophmayrhofer** [openlayers/ol3-cesium#434]
I have managed to enable lighting: 
map.ol3d = new olcs.OLCesium({map: map});
map.ol3d.getCesiumScene().globe.enableLighting = true;

I would now need to set the clock time in order to move the sun position. How can I access the appropriate clock instance that is used in the OLCesium instance?

**Comment by gberaudo** [comment]
You can provide your own time function in the constructor, see https://github.com/openlayers/ol3-cesium/blob/master/src/ol3cesium.js#L34.

**Comment by christophmayrhofer** [comment]
Thank you for the quick reply. I tried to supply a time function, but it does not seem to get called when I move the scene/globe:

  map.ol3d = new olcs.OLCesium({map: map, time: function(){ 
	console.log('time', this..time);
	return Cesium.JulianDate(this.time);
  }});
  map.ol3d.time = new Date(timestamp);

**Comment by oterral** [comment]
Are you sure the `this` is currently the ol3d object ?

**Comment by christophmayrhofer** [comment]
I cannot really test what this is at runtime, since I couldn't manage to trigger the time function in the first place (i.e. console.log does not get executed)

**Comment by gberaudo** [comment]
You can put a breakpoint in `olcs.OLCesium.prototype.onAnimationFrame_`; the time function is called there.

**Comment by christophmayrhofer** [comment]
Turns out that the issue was with the JulianDate function. It needs to be Cesium.JulianDate.fromDate -->

```
map.ol3d = new olcs.OLCesium({map: map, time: function(){ 
	return Cesium.JulianDate.fromDate(this.time || new Date());
  }});
  map.ol3d.time = new Date('2017-01-20T12:00:00Z');
```
